// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function Create(arg1, arg2) {
  return window['go']['app']['App']['Create'](arg1, arg2);
}

export function Delete(arg1) {
  return window['go']['app']['App']['Delete'](arg1);
}

export function Duplicate(arg1) {
  return window['go']['app']['App']['Duplicate'](arg1);
}

export function GRPCMethods(arg1) {
  return window['go']['app']['App']['GRPCMethods'](arg1);
}

export function GRPCQueryFake(arg1, arg2) {
  return window['go']['app']['App']['GRPCQueryFake'](arg1, arg2);
}

export function GRPCQueryValidate(arg1, arg2, arg3) {
  return window['go']['app']['App']['GRPCQueryValidate'](arg1, arg2, arg3);
}

export function Get(arg1) {
  return window['go']['app']['App']['Get'](arg1);
}

export function JQ(arg1, arg2) {
  return window['go']['app']['App']['JQ'](arg1, arg2);
}

export function List() {
  return window['go']['app']['App']['List']();
}

export function Perform(arg1) {
  return window['go']['app']['App']['Perform'](arg1);
}

export function Read(arg1) {
  return window['go']['app']['App']['Read'](arg1);
}

export function Rename(arg1, arg2) {
  return window['go']['app']['App']['Rename'](arg1, arg2);
}

export function Update(arg1, arg2, arg3) {
  return window['go']['app']['App']['Update'](arg1, arg2, arg3);
}
