// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {app} from '../models';
import {database} from '../models';

export function Create(arg1:string,arg2:string):Promise<app.ResponseNewRequest>;

export function Delete(arg1:string):Promise<void>;

export function Duplicate(arg1:string):Promise<void>;

export function GRPCMethods(arg1:string):Promise<Array<app.grpcServiceMethods>>;

export function GRPCQueryFake(arg1:string,arg2:string):Promise<string>;

export function GRPCQueryValidate(arg1:string,arg2:string,arg3:string):Promise<void>;

export function JQ(arg1:string,arg2:string):Promise<Array<string>>;

export function List():Promise<app.ListResponse>;

export function Perform(arg1:string):Promise<Record<string, any>>;

export function Read(arg1:string):Promise<database.Request>;

export function Update(arg1:string,arg2:string,arg3:string,arg4:Record<string, any>):Promise<void>;
