// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function ExportTypes(arg1, arg2, arg3, arg4, arg5, arg6, arg7, arg8, arg9, arg10) {
  return window['go']['main']['export']['ExportTypes'](arg1, arg2, arg3, arg4, arg5, arg6, arg7, arg8, arg9, arg10);
}
