// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {database} from '../models';

export function ExportTypes(arg1:database.HTTPRequest,arg2:database.HTTPResponse,arg3:database.SQLRequest,arg4:database.SQLResponse,arg5:database.GRPCRequest,arg6:database.GRPCResponse,arg7:database.JQRequest,arg8:database.JQResponse,arg9:database.RedisRequest,arg10:database.RedisResponse,arg11:database.MarkdownRequest,arg12:database.MarkdownResponse):Promise<void>;
