// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {database} from '../models';

export function ExportTypes(arg1:database.HTTPRequest,arg2:database.RedisRequest):Promise<void>;
